### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by loboris** [joysfera/esp-idf-spiffs#1]
Not an issue, but have you seen this:
[SPIFFS on ESP32](https://github.com/loboris/ESP32_spiffs_example) ([Forum](https://www.esp32.com/viewtopic.php?f=18&t=1901))
I think it's more complete, with more features and examples.

I appreciate your work, but why duplicate the same thing.

Best regards.

**Comment by joysfera** [comment]
I didn't know about it, of course. Google didn't find it for me. Thanks for the pointer.
